This is makeindex, version 2.15 [TeX Live 2016] (kpathsea + Thai support).
Scanning style file ./totaal.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file totaal.acn....done (3 entries accepted, 0 rejected).
Sorting entries....done (4 comparisons).
Generating output file totaal.acr....done (12 lines written, 0 warnings).
Output written in totaal.acr.
Transcript written in totaal.alg.
